#ifndef ARDUINO_HOSTUINO_EXTRAS_HOST_ETHERNET5500_ETHERNET_CONFIG_H_
#define ARDUINO_HOSTUINO_EXTRAS_HOST_ETHERNET5500_ETHERNET_CONFIG_H_

#include <inttypes.h>

namespace alpaca {

typedef uint8_t SOCKET;
#define MAX_SOCK_NUM 8

}  // namespace alpaca

#endif  // ARDUINO_HOSTUINO_EXTRAS_HOST_ETHERNET5500_ETHERNET_CONFIG_H_
